version: '3.8'

services: 
  app:
    image: frontend-dev
    build:
      context: ./frontend/  
      dockerfile: ./frontend/dev.Dockerfile 
    volumes:
      - ./frontend/:/usr/src/app  
    ports:
       - 3000:3000
    container_name: my-app-frontend-dev 
  server:
    image: backend-dev
    build:
       context: ./backend/
       dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    container_name: my-app-server-dev 
  #TODO: 
  # environment:
  #   - MONGO_URL= graphql ympäristön url
  debug-helper:
    image: busybox 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy-dev 
