version: '3.8'

services: 
  app:
    image: frontend
    build:
      context: ./frontend/  
      dockerfile: ./frontend/Dockerfile 
    volumes:
      - ./frontend/:/usr/src/app  
    ports:
       - 3000:3000
    container_name: my-app-frontend-prod
  server:
    image: backend
    build:
       context: ./backend/
       dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    container_name: my-app-server-prod 
  #TODO: 
  # environment:
  #   - MONGO_URL= graphql ympäristön url
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy-prod 