version: '3.8'

services: 
  app:
    image: frontend-dev
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: ./frontend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
       - 3000:3000
    container_name: my-app-frontend-dev 
    
  server:
    image: backend-dev
    build:
       context: ./backend/
       dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    container_name: my-app-server-dev
    # environment:  
    #   - MONGO_URL="mongodb://root:example@mongo:27017" 
  debug-helper:
    image: busybox 

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy 
    
volumes:
  mongo_data:
